services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=https://qqgrckeazwunfaoujjkt.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZ3Jja2Vhend1bmZhb3Vqamt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjE4MDAsImV4cCI6MjA2MDA5NzgwMH0.Ssh7Z-RiQeb1hVlsdcABZufCMwrozepxchVwl_eamTo
    depends_on:
      - postgres

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: recr_monkey_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: